# entr
FROM lagden/entr:4.7-alpine3.13 as entr

LABEL autodelete="true"
LABEL maintainer="lagden@gmail.com"

# APP Dev
FROM node:14.15-alpine3.12

LABEL maintainer="lagden@gmail.com"

## If Docker Host is Mac or Windows
ARG ARG_ENTR_INOTIFY_WORKAROUND=0
RUN test $ARG_ENTR_INOTIFY_WORKAROUND -eq 1 && . ENTR_INOTIFY_WORKAROUND=1 || echo "ENTR_INOTIFY_WORKAROUND unnecessary"

ARG NODE_ENV="production"
ARG BASE="/home/node"

ENV NODE_ENV=$NODE_ENV
ENV BASE=$BASE
ENV BASE_APP=$BASE/app

WORKDIR /usr/local/bin
COPY --from=entr /usr/local/bin/entr .

WORKDIR $BASE

ADD --chown=node:node . $BASE_APP

WORKDIR $BASE_APP

RUN npm ci --ignore-scripts

USER node
