# entr
FROM lagden/entr:4.7-alpine3.13 as entr
LABEL autodelete="true"
LABEL maintainer="lagden@gmail.com"

# -----

# APP Dev
FROM node:14.15-alpine3.13
LABEL maintainer="lagden@gmail.com"

## If Docker Host is Mac or Windows
ENV ENTR_INOTIFY_WORKAROUND=1

ARG NODE_ENV="production"
ARG BASE="/home/node"

ENV NODE_ENV=$NODE_ENV
ENV BASE=$BASE
ENV BASE_APP=$BASE/app

COPY --from=entr /usr/local/bin/entr /usr/local/bin/.

WORKDIR $BASE
ADD --chown=node:node . $BASE_APP

WORKDIR $BASE_APP
# RUN npm i -g npm
# RUN npm --version
RUN npm ci --ignore-scripts --also=dev

USER node
